### ISSUE TITLE
Is there any way to get the item index?

### ISSUE THREAD

**Issue by irfnyas** [cregus/simple-recyclerview-adapter#1]
Hi, from the example below, is there any way to get the **item** index/position from its list?
```
 R.layout.item_header -> viewHolder<Header>(view) { item ->
            label.text = item.label
 }
```

**Comment by cregus** [comment]
Currently you can get it only by using `items.indexOf(item)`.
I'll think about adding `position` parameter to make it easier.

**Comment by cregus** [comment]
Whole library has been rewritten in version 1.1.0 to support Jetpack View Binding and from now position is passed to binding function.
