### ISSUE TITLE
Adapter.notifyDataSetChanged() not working

### ISSUE THREAD

**Issue by irfnyas** [cregus/simple-recyclerview-adapter#2]
Hi, I have a problem after adding new items to the list. It seems the view is not updated after I use adapter.notifyDataSetChanged(). Do you have any solution for this? Thanks

**Comment by cregus** [comment]
Have you tried to use `adapter.submitList(items)` after your list has been updated?

**Comment by irfnyas** [comment]
I tried and it works nicely, thanks
